name: Run unit tests for react app

on: push

jobs:
  run-tests:
    runner: ubuntu-22.04
    steps:
      - name: Fetch the code from hosted repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test